{
 "title": "Dades Covid Dashboard",
 "time": { "from": "2019-05-31T11:29:03.377Z", "to": "2021-06-01T11:29:03.377Z" },
 "panels": [
  {
   "title": "14-day Cumulative Incidence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ci14" }
   ]
  },
  {
   "title": "Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "cases" }
   ]
  },
  {
   "title": "Outbreak Risk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "outbreak" }
   ]
  },
  {
   "title": "Hospitalized",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "hospitalized" },
    { "target": "icu" },
    { "target": "deaths" }
   ]
  },
  {
   "title": "Disease Reproduction Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "rt" }
   ]
  }
 ]
}